# NIM Deployment Configuration
# Meta Llama 3.1 8B Instruct on OKE

replicaCount: 1

image:
  registry: nvcr.io
  repository: nim/meta/llama-3.1-8b-instruct
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ngc-secret

ngc:
  apiKey: "<YOUR_NGC_API_KEY>"
  registry: nvcr.io
  username: "$oauthtoken"

model:
  name: "meta/llama-3.1-8b-instruct"
  cache:
    enabled: true
    storageClass: "oci-bv"
    size: "50Gi"

resources:
  limits:
    nvidia.com/gpu: 1
    memory: "32Gi"
    cpu: "8"
  requests:
    nvidia.com/gpu: 1
    memory: "24Gi"
    cpu: "4"

service:
  type: LoadBalancer
  port: 8000
  targetPort: 8000
  externalTrafficPolicy: Local
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "10"

env:
  - name: NIM_CACHE_PATH
    value: "/model-cache"
  - name: NIM_MODEL_PROFILE
    value: "auto"
  - name: NGC_API_KEY
    valueFrom:
      secretKeyRef:
        name: nvidia-nim-ngc-api
        key: NGC_API_KEY

persistence:
  enabled: true
  storageClass: "oci-bv"
  accessMode: ReadWriteOnce
  size: 50Gi
  mountPath: /model-cache

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false

nodeSelector:
  nvidia.com/gpu.product: NVIDIA-A10

tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: nvidia.com/gpu.present
              operator: In
              values:
                - "true"

topologySpreadConstraints:
  enabled: true
  maxSkew: 1
  topologyKey: topology.kubernetes.io/zone
  whenUnsatisfiable: DoNotSchedule

readinessProbe:
  httpGet:
    path: /v1/health/ready
    port: 8000
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /v1/health/live
    port: 8000
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 3

startupProbe:
  httpGet:
    path: /v1/health/startup
    port: 8000
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 30

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8000"
  prometheus.io/path: "/metrics"

serviceAccount:
  create: true
  annotations:
    oci.oraclecloud.com/principal-type: "instance"
  name: "nim-service-account"

labels:
  app.kubernetes.io/name: nvidia-nim
  app.kubernetes.io/component: inference
  app.kubernetes.io/part-of: nim-deployment

costOptimization:
  scheduleDowntime: false

